# Use `hub`
if hash hub &> /dev/null
then
  eval "$(hub alias -s)"
fi

alias g..='cd $(git rev-parse --show-toplevel)'
alias g='git'
alias ga='git add'
alias gaa='git add -A'
alias gap='git add -p'
alias gb='git branch'
alias gc='git commit'
alias gca='git commit -a'
alias gcam='git commit -a -m'
alias gcl='git clone'
alias gcm='git commit -m'
alias gco='git checkout'
alias gcod='git checkout develop'
alias gcom='git checkout master'
alias gd='git diff'
alias gf='git fetch'
alias gfu='git fetch upstream'
alias gh='git help'
alias gl='git log'
alias glg='git lg'
alias gm='git merge'
alias gmv='git mv'
alias gp='git push'
alias gpo='git push origin'
alias gpoa='git push origin --all'
alias gpod='git push origin develop'
alias gpof='git push origin --force --no-verify'
alias gpom='git push origin master'
alias gpu='git pull'
alias gr='git remote'
alias gra='git remote add'
alias grau='git remote add upstream'
alias gre='git rebase'
alias grei='git rebase -i'
alias grm='git rm'
alias grmad='cd $(git rev-parse --show-toplevel); gs --porcelain | egrep "^ D" | cut -c 4- | xargs git rm; cd -'
alias grv='git remote -v'
alias gs='git status'
alias gsa='git stash apply'
alias gss='git stash save'
alias gst='git stash'
alias gt='git tag'
